name: library_manage_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4  # Add the latest version of sqflite
  path_provider: ^2.0.2  # For getting the correct file path
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, ensure this section is uncommented and correctly indented.
  assets:
    - assets/images/
